name: ping_win32
description: A simple wrapper for Win32 IcmpSendEcho2 function
version: 0.0.2
repository: https://github.com/espresso3389/ping_win32

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  lints: ^2.1.0

platforms:
  windows:
